# Generated by Django 5.2.8 on 2025-11-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="page_size",
            field=models.PositiveIntegerField(
                choices=[(10, "10"), (20, "20"), (50, "50")],
                default=20,
                verbose_name="Размер страницы",
            ),
        ),
    ]
