# Generated by Django 5.2.8 on 2025-11-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usersettings_page_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="saved_filters",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Сохранённые фильтры"
            ),
        ),
    ]
