# Generated by Django 5.2.8 on 2025-11-25 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text='Имя таблицы/модели, над которой выполнялась операция.', max_length=128, verbose_name='Таблица')),
                ('operation', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Изменение'), ('DELETE', 'Удаление'), ('LOGIN', 'Вход в систему'), ('OTHER', 'Другое')], max_length=16, verbose_name='Операция')),
                ('object_pk', models.CharField(blank=True, help_text='Первичный ключ записи (если есть).', max_length=64, verbose_name='ID объекта')),
                ('data_before', models.JSONField(blank=True, null=True, verbose_name='Данные до')),
                ('data_after', models.JSONField(blank=True, null=True, verbose_name='Данные после')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время операции')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'db_table': 'audit_log',
                'ordering': ('-created_at',),
            },
        ),
    ]
